version: "3"
services:
  node-app:
    container_name: express-container
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
