version: "3"
services:
  node-app:
    volumes:
      - ./src:/app/src:ro
    build:
      context: .
      target: production
    environment:
      - NODE_ENV=production
    #To override run command
    command: npm run start
